### ISSUE TITLE
WKT not supported (yet?) as geometry parameter

### ISSUE THREAD

**Issue by StefanBrand** [dcs4cop/xcube-sh#4]
According to `xcube sh gen --help` we can feed arbitrary geometries to `xcube sh gen` :

```
  -g, --geom TEXT                Geometry WKT, GeoJSON object, or bounding box
                                 using format "<lon1>,<lat1>,<lon2>,<lat2>".
                                 Coordinates must be in decimal degree.
                                 [required]
```

## This works (bbox):
```bash
xcube sh gen S2L2A -o ooe.zarr -b B04 -g 14.318395625014208,48.359153946428485,14.506361110382839,48.543395524629055 -r 0.000134 -t 2018-01-01,2018-01-31 -p 2D
```

## This doesn't work (wkt): 
```bash
xcube sh gen S2L2A -o ooe_wkt.zarr -b B04 -g "POLYGON ((14.31839562501421 48.35915394642848, 14.50636111038284 48.35915394642848, 14.50636111038284 48.54339552462906, 14.31839562501421 48.54339552462906, 14.31839562501421 48.35915394642848))" -r 0.000134 -t 2018-01-01,2018-01-31 -p 2D
```
fails with error message:
```bash
Internal error: could not convert string to float: 'POLYGON ((14.31839562501421 48.35915394642848'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/xcube/cli/main.py", line 52, in main
    exit_code = cli.main(args=args, obj=ctx_obj, standalone_mode=False)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/xcube_sh/cli.py", line 116, in gen
    exception_type=click.ClickException)
  File "/opt/conda/lib/python3.7/site-packages/xcube_sh/config.py", line 79, in __init__
    x1, y1, x2, y2 = tuple(map(float, geometry.split(',', maxsplit=3)))
ValueError: could not convert string to float: 'POLYGON ((14.31839562501421 48.35915394642848'
```

## Environment
- Euro Data Cube / Jupyter Hub Terminal
- xcube version: `xcube, version 0.4.0.dev0`
- xcube_sh version: `xcube, version 0.3.0.dev0`

**Comment by forman** [comment]
@StefanBrand thanks for reporting! Correct, WKT hasn't been implemented yet. We should use a `bbox` keyword instead to avoid false hopes...

**Comment by forman** [comment]
Bug: should either support WKT or correct description.

**Comment by forman** [comment]
Using `bbox` now, `geometry` is deprecated.
